name: Update Organization Display Name

on:
  schedule:
    - cron: '0 0 * * *'  # This will trigger the action at midnight UTC every day
  workflow_dispatch:

jobs:
  update-org-display-name:
    runs-on: ubuntu-latest

    steps:
      - name: Set today's date as the display name
        run: |
          # Get today's date in the format "DD/MM/YYYY"
          DISPLAY_NAME="Satta Matka DpBoss King Kalyan Result [LIVE] $(date +'%d/%m/%Y') : ये लकी लोग रातों-रात बने करोड़पति, देखें विनिंग नंबर"

          # Update the organization's display name using GitHub API
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.ORG_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"name\":\"$DISPLAY_NAME\"}" \
            https://api.github.com/orgs/satta-matka-dpboss-king-kalyan-result
        env:
          DISPLAY_NAME: ""
